# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20161021_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_text',
            new_name='text',
        ),
    ]
